Initial Apply job changes
hims1911/null-jobs-backend pull request #1
Opened 2023-09-08 17:41 UTC by Himan10

Fixes: 
1. Might be having some template rendering issues while calling jobs/company APIs, because both these APIs use some filters for searching results, so in this case, adding `django_filters` to the settings.py will resolve this issue. [Reference](https://github.com/carltongibson/django-filter/issues/562)
2. In the requirements.txt, replace the package `backports.zoneinfo==0.2.1` with `backports.zoneinfo;python_version<"3.9"`. Avoid installing this package for python versions > 3.9

Added:
1. new model (applicants) in `apps/jobs/models.py`
2. Create an action under the Job viewset to handle the apply functionality (initial)

2023-09-08 18:30 UTC, HimanshuSharma-Angel requested changes

2023-09-08 18:30 UTC, HimanshuSharma-Angel commented on apps/jobs/models.py
> +    ("under-reviewed", "Under-Reviewed"),
status choice would be initiated

2023-09-08 18:30 UTC, HimanshuSharma-Angel commented on apps/jobs/models.py
> +    resume = models.FileField(upload_to="resume/", null=True, blank=True)
we dont need it as we can fetch it from user table

2023-09-08 20:11 UTC, hims1911 requested changes

2023-09-08 20:11 UTC, hims1911 commented on apps/jobs/views.py
> +        if "user_id" not in request.data:
for time being its ok but in future will fetch from JWT

2023-09-08 20:11 UTC, hims1911 commented on apps/jobs/views.py
> +
we can club both the statement.

2023-09-08 20:11 UTC, hims1911 commented on apps/jobs/views.py
> +
lets discuss this tomorrow.

2023-09-09 06:47 UTC, hims1911 commented on apps/jobs/views.py
> +
`if validate_id(job_id, "job-id", Job) and  response = validate_id(user_id, "user-id", User):
    return generic response() 
`

2023-09-09 06:48 UTC, hims1911 commented on apps/jobs/views.py
> +            if not value:
optimise this

2023-09-09 06:50 UTC, hims1911 commented on apps/jobs/views.py
> +        applyjob = Applicants(**applyjob_data)
default choice - initiated

hr update -> status 

applyjob_data["status"] = request.data["status"]

2023-09-09 07:03 UTC, hims1911 requested changes

2023-09-09 07:03 UTC, hims1911 commented on apps/jobs/views.py
> +        applyjob = Applicants(**applyjob_data)
`if user_type is HR`

2023-09-12 16:20 UTC, merged